CREATE TABLE IF NOT EXISTS match_summaries (
    id SERIAL PRIMARY KEY,
    match_id INT UNIQUE REFERENCES matches (id) ON DELETE CASCADE,
    home_score INT DEFAULT 0,
    away_score INT DEFAULT 0,
    possession_home DECIMAL(5, 2),
    possession_away DECIMAL(5, 2),
    shots_home INT,
    shots_away INT,
    shots_on_target_home INT,
    shots_on_target_away INT,
    corners_home INT,
    corners_away INT,
    fouls_home INT,
    fouls_away INT,
    offsides_home INT,
    offsides_away INT,
    yellow_home INT,
    yellow_away INT,
    red_home INT,
    red_away INT,
    created_at TIMESTAMP DEFAULT NOW(),
    updated_at TIMESTAMP DEFAULT NOW()
);